### ISSUE TITLE
make responsive

### ISSUE THREAD

**Issue by apuayush** [apuayush/quizzy-api#14]
make all html pages responsive

**Comment by MatthewElson** [comment]
Still need help with this?

**Comment by apuayush** [comment]
Yeaa. If u cld

**Comment by MatthewElson** [comment]
Hey @apuayush, I've finished the collective html page. I wasn't going to create a pull request until I finished the rest of the pages. What's the best way to show you what I've done so far?

**Comment by apuayush** [comment]
You better create a pull request. You can add commits on that PR and I can check that PR without merging it until you have completed

**Comment by MatthewElson** [comment]
pr #15 created

**Comment by MatthewElson** [comment]
@apuayush  I've made all (actually most, some I thought were fine as is) pages responsive.

**Comment by apuayush** [comment]
yea thank you i have merged the PR.
