### ISSUE TITLE
validate password strength and email format and all other input filled at signup

### ISSUE THREAD

**Issue by apuayush** [apuayush/quizzy-api#7]
in log1.html linked with log.js validate password and email format . and check if all the inputs are filled or not.

**Comment by alexoch** [comment]
Hi, I can try try to help you)

**Comment by apuayush** [comment]
yea that would be good..

**Comment by alexoch** [comment]
Is there any rules for passwords in your project?

**Comment by apuayush** [comment]
yea more than characters and strong (which you can decide). there is a function in log.js check_password you can make changes to that and implement it.

**Comment by alexoch** [comment]
yea, I've found it, try my best

**Comment by apuayush** [comment]
ping me when you are done

**Comment by alexoch** [comment]
Apurva, can you help me plz. I've prepared all the code but have troubles with submmiting it

**Comment by apuayush** [comment]
yea whats the problem ?

**Comment by adi0602** [comment]
is it still open?
is there something I can help you with?

**Comment by apuayush** [comment]
its done.
